version: '3'

services:
  jekyll:
    container_name: challenges
    image: jekyll/jekyll
    command: "jekyll serve"
    ports:
      - "4000:4000"
    volumes:
      - ".:/srv/jekyll"
      - "./vendor/bundle:/usr/local/bundle"
